/**
 * Option arrays del form automation — estratte VERBATIM da
 * automation-form.component.ts (label = chiavi i18n `automation.*`
 * o stringhe fisse; value = valori attesi dal contratto API).
 */

export const genderOptions = ['Male', 'Female', 'Company'];
export const languageOptions = [
  { value: 'de', label: 'Deutsch' },
  { value: 'en', label: 'English' },
  { value: 'fr', label: 'Français' },
  { value: 'it', label: 'Italiano' },
];
export const foreignersIdOptions = [
  { value: 'B', label: 'automation.opt_permit_B' },
  { value: 'C', label: 'automation.opt_permit_C' },
  { value: 'S', label: 'automation.opt_permit_S' },
  { value: 'Ci', label: 'automation.opt_permit_Ci' },
  { value: 'F', label: 'automation.opt_permit_F' },
  { value: 'G', label: 'automation.opt_permit_G' },
  { value: 'N', label: 'automation.opt_permit_N' },
];
export const nationalityOptions = [
  { value: 'CH', label: 'Svizzera' },
  { value: 'DE', label: 'Germania' },
  { value: 'IT', label: 'Italia' },
  { value: 'FR', label: 'Francia' },
  { value: 'AF', label: 'Afghanistan' },
  { value: 'AL', label: 'Albania' },
  { value: 'DZ', label: 'Algeria' },
  { value: 'AD', label: 'Andorra' },
  { value: 'AO', label: 'Angola' },
  { value: 'AG', label: 'Antigua e Barbuda' },
  { value: 'AR', label: 'Argentina' },
  { value: 'AM', label: 'Armenia' },
  { value: 'AU', label: 'Australia' },
  { value: 'AT', label: 'Austria' },
  { value: 'AZ', label: 'Azerbaigian' },
  { value: 'BS', label: 'Bahamas' },
  { value: 'BH', label: 'Bahrein' },
  { value: 'BD', label: 'Bangladesh' },
  { value: 'BB', label: 'Barbados' },
  { value: 'BY', label: 'Bielorussia' },
  { value: 'BE', label: 'Belgio' },
  { value: 'BZ', label: 'Belize' },
  { value: 'BJ', label: 'Benin' },
  { value: 'BT', label: 'Bhutan' },
  { value: 'BO', label: 'Bolivia' },
  { value: 'BA', label: 'Bosnia ed Erzegovina' },
  { value: 'BW', label: 'Botswana' },
  { value: 'BR', label: 'Brasile' },
  { value: 'BN', label: 'Brunei' },
  { value: 'BG', label: 'Bulgaria' },
  { value: 'BF', label: 'Burkina Faso' },
  { value: 'BI', label: 'Burundi' },
  { value: 'KH', label: 'Cambogia' },
  { value: 'CM', label: 'Camerun' },
  { value: 'CA', label: 'Canada' },
  { value: 'CV', label: 'Capo Verde' },
  { value: 'TD', label: 'Ciad' },
  { value: 'CL', label: 'Cile' },
  { value: 'CN', label: 'Cina' },
  { value: 'CY', label: 'Cipro' },
  { value: 'CO', label: 'Colombia' },
  { value: 'KM', label: 'Comore' },
  { value: 'CG', label: 'Congo' },
  { value: 'CD', label: 'Congo, Repubblica Democratica' },
  { value: 'KP', label: 'Corea del Nord' },
  { value: 'KR', label: 'Corea del Sud' },
  { value: 'CI', label: "Costa d'Avorio" },
  { value: 'CR', label: 'Costa Rica' },
  { value: 'HR', label: 'Croazia' },
  { value: 'CU', label: 'Cuba' },
  { value: 'DK', label: 'Danimarca' },
  { value: 'DM', label: 'Dominica' },
  { value: 'DO', label: 'Repubblica Dominicana' },
  { value: 'EC', label: 'Ecuador' },
  { value: 'EG', label: 'Egitto' },
  { value: 'SV', label: 'El Salvador' },
  { value: 'AE', label: 'Emirati Arabi Uniti' },
  { value: 'ER', label: 'Eritrea' },
  { value: 'EE', label: 'Estonia' },
  { value: 'ET', label: 'Etiopia' },
  { value: 'FJ', label: 'Figi' },
  { value: 'PH', label: 'Filippine' },
  { value: 'FI', label: 'Finlandia' },
  { value: 'GA', label: 'Gabon' },
  { value: 'GM', label: 'Gambia' },
  { value: 'GE', label: 'Georgia' },
  { value: 'GH', label: 'Ghana' },
  { value: 'JM', label: 'Giamaica' },
  { value: 'JP', label: 'Giappone' },
  { value: 'DJ', label: 'Gibuti' },
  { value: 'JO', label: 'Giordania' },
  { value: 'GR', label: 'Grecia' },
  { value: 'GD', label: 'Grenada' },
  { value: 'GT', label: 'Guatemala' },
  { value: 'GN', label: 'Guinea' },
  { value: 'GW', label: 'Guinea-Bissau' },
  { value: 'GQ', label: 'Guinea Equatoriale' },
  { value: 'GY', label: 'Guyana' },
  { value: 'HT', label: 'Haiti' },
  { value: 'HN', label: 'Honduras' },
  { value: 'IN', label: 'India' },
  { value: 'ID', label: 'Indonesia' },
  { value: 'IR', label: 'Iran' },
  { value: 'IQ', label: 'Iraq' },
  { value: 'IE', label: 'Irlanda' },
  { value: 'IS', label: 'Islanda' },
  { value: 'IL', label: 'Israele' },
  { value: 'KZ', label: 'Kazakistan' },
  { value: 'KE', label: 'Kenya' },
  { value: 'KG', label: 'Kirghizistan' },
  { value: 'KI', label: 'Kiribati' },
  { value: 'XK', label: 'Kosovo' },
  { value: 'KW', label: 'Kuwait' },
  { value: 'LA', label: 'Laos' },
  { value: 'LS', label: 'Lesotho' },
  { value: 'LV', label: 'Lettonia' },
  { value: 'LB', label: 'Libano' },
  { value: 'LR', label: 'Liberia' },
  { value: 'LY', label: 'Libia' },
  { value: 'LI', label: 'Liechtenstein' },
  { value: 'LT', label: 'Lituania' },
  { value: 'LU', label: 'Lussemburgo' },
  { value: 'MK', label: 'Macedonia del Nord' },
  { value: 'MG', label: 'Madagascar' },
  { value: 'MW', label: 'Malawi' },
  { value: 'MY', label: 'Malaysia' },
  { value: 'MV', label: 'Maldive' },
  { value: 'ML', label: 'Mali' },
  { value: 'MT', label: 'Malta' },
  { value: 'MA', label: 'Marocco' },
  { value: 'MH', label: 'Isole Marshall' },
  { value: 'MR', label: 'Mauritania' },
  { value: 'MU', label: 'Mauritius' },
  { value: 'MX', label: 'Messico' },
  { value: 'FM', label: 'Micronesia' },
  { value: 'MD', label: 'Moldavia' },
  { value: 'MC', label: 'Monaco' },
  { value: 'MN', label: 'Mongolia' },
  { value: 'ME', label: 'Montenegro' },
  { value: 'MZ', label: 'Mozambico' },
  { value: 'MM', label: 'Myanmar' },
  { value: 'NA', label: 'Namibia' },
  { value: 'NR', label: 'Nauru' },
  { value: 'NP', label: 'Nepal' },
  { value: 'NI', label: 'Nicaragua' },
  { value: 'NE', label: 'Niger' },
  { value: 'NG', label: 'Nigeria' },
  { value: 'NO', label: 'Norvegia' },
  { value: 'NZ', label: 'Nuova Zelanda' },
  { value: 'NL', label: 'Paesi Bassi' },
  { value: 'PK', label: 'Pakistan' },
  { value: 'PW', label: 'Palau' },
  { value: 'PS', label: 'Palestina' },
  { value: 'PA', label: 'Panama' },
  { value: 'PG', label: 'Papua Nuova Guinea' },
  { value: 'PY', label: 'Paraguay' },
  { value: 'PE', label: 'Perù' },
  { value: 'PL', label: 'Polonia' },
  { value: 'PT', label: 'Portogallo' },
  { value: 'GB', label: 'Regno Unito' },
  { value: 'CF', label: 'Repubblica Centrafricana' },
  { value: 'CZ', label: 'Repubblica Ceca' },
  { value: 'RO', label: 'Romania' },
  { value: 'RW', label: 'Ruanda' },
  { value: 'RU', label: 'Russia' },
  { value: 'KN', label: 'Saint Kitts e Nevis' },
  { value: 'LC', label: 'Santa Lucia' },
  { value: 'VC', label: 'Saint Vincent e Grenadine' },
  { value: 'WS', label: 'Samoa' },
  { value: 'SM', label: 'San Marino' },
  { value: 'ST', label: 'São Tomé e Príncipe' },
  { value: 'SA', label: 'Arabia Saudita' },
  { value: 'SN', label: 'Senegal' },
  { value: 'RS', label: 'Serbia' },
  { value: 'SC', label: 'Seychelles' },
  { value: 'SL', label: 'Sierra Leone' },
  { value: 'SG', label: 'Singapore' },
  { value: 'SK', label: 'Slovacchia' },
  { value: 'SI', label: 'Slovenia' },
  { value: 'SB', label: 'Isole Salomone' },
  { value: 'SO', label: 'Somalia' },
  { value: 'ES', label: 'Spagna' },
  { value: 'LK', label: 'Sri Lanka' },
  { value: 'US', label: 'Stati Uniti' },
  { value: 'ZA', label: 'Sudafrica' },
  { value: 'SD', label: 'Sudan' },
  { value: 'SS', label: 'Sudan del Sud' },
  { value: 'SR', label: 'Suriname' },
  { value: 'SE', label: 'Svezia' },
  { value: 'SZ', label: 'Eswatini' },
  { value: 'SY', label: 'Siria' },
  { value: 'TJ', label: 'Tagikistan' },
  { value: 'TW', label: 'Taiwan' },
  { value: 'TZ', label: 'Tanzania' },
  { value: 'TH', label: 'Thailandia' },
  { value: 'TL', label: 'Timor Est' },
  { value: 'TG', label: 'Togo' },
  { value: 'TO', label: 'Tonga' },
  { value: 'TT', label: 'Trinidad e Tobago' },
  { value: 'TN', label: 'Tunisia' },
  { value: 'TR', label: 'Turchia' },
  { value: 'TM', label: 'Turkmenistan' },
  { value: 'TV', label: 'Tuvalu' },
  { value: 'UA', label: 'Ucraina' },
  { value: 'UG', label: 'Uganda' },
  { value: 'HU', label: 'Ungheria' },
  { value: 'UY', label: 'Uruguay' },
  { value: 'UZ', label: 'Uzbekistan' },
  { value: 'VU', label: 'Vanuatu' },
  { value: 'VA', label: 'Vaticano' },
  { value: 'VE', label: 'Venezuela' },
  { value: 'VN', label: 'Vietnam' },
  { value: 'YE', label: 'Yemen' },
  { value: 'ZM', label: 'Zambia' },
  { value: 'ZW', label: 'Zimbabwe' },
];
export const currentInsuranceOptions = [
  { value: 'keine', label: 'automation.opt_ins_none' },
  { value: 'neu in der Schweiz', label: 'automation.opt_ins_new_ch' },
  { value: 'Automate', label: 'automation.opt_ins_automate' },
  { value: 'Allianz Suisse', label: 'automation.opt_ins_allianz' },
  { value: 'AXA', label: 'automation.opt_ins_axa' },
  { value: 'Baloise', label: 'automation.opt_ins_baloise' },
  { value: 'Belsura', label: 'automation.opt_ins_belsura' },
  { value: 'Elvia', label: 'automation.opt_ins_elvia' },
  { value: 'Generali', label: 'automation.opt_ins_generali' },
  { value: 'Helvetia', label: 'automation.opt_ins_helvetia' },
  { value: 'Migros', label: 'automation.opt_ins_migros' },
  { value: 'Mobiliar', label: 'automation.opt_ins_mobiliar' },
  { value: 'Postfinance', label: 'automation.opt_ins_postfinance' },
  { value: 'smile.direct', label: 'automation.opt_ins_smile' },
  { value: 'Simpego', label: 'automation.opt_ins_simpego' },
  { value: 'TCS', label: 'automation.opt_ins_tcs' },
  { value: 'TSM', label: 'automation.opt_ins_tsm' },
  { value: 'Vaudoise', label: 'automation.opt_ins_vaudoise' },
  { value: 'Visana', label: 'automation.opt_ins_visana' },
  { value: 'Zürich', label: 'automation.opt_ins_zurich' },
  { value: 'Andere Versicherung', label: 'automation.opt_ins_other' },
  { value: 'Versicherung im Ausland', label: 'automation.opt_ins_abroad' },
];
export const cantonOptions = [
  { value: 'AR', label: 'AR Appenzello Esterno' },
  { value: 'AI', label: 'AI Appenzello Interno' },
  { value: 'AG', label: 'AG Argovia' },
  { value: 'BL', label: 'BL Basilea Campagna' },
  { value: 'BS', label: 'BS Basilea Città' },
  { value: 'BE', label: 'BE Berna' },
  { value: 'FR', label: 'FR Friburgo' },
  { value: 'GE', label: 'GE Ginevra' },
  { value: 'JU', label: 'JU Giura' },
  { value: 'GL', label: 'GL Glarona' },
  { value: 'GR', label: 'GR Grigioni' },
  { value: 'LU', label: 'LU Lucerna' },
  { value: 'NE', label: 'NE Neuchâtel' },
  { value: 'NW', label: 'NW Nidvaldo' },
  { value: 'OW', label: 'OW Obvaldo' },
  { value: 'SG', label: 'SG San Gallo' },
  { value: 'SH', label: 'SH Sciaffusa' },
  { value: 'SO', label: 'SO Soletta' },
  { value: 'SZ', label: 'SZ Svitto' },
  { value: 'TI', label: 'TI Ticino' },
  { value: 'TG', label: 'TG Turgovia' },
  { value: 'UR', label: 'UR Uri' },
  { value: 'VS', label: 'VS Vallese' },
  { value: 'VD', label: 'VD Vaud' },
  { value: 'ZG', label: 'ZG Zugo' },
  { value: 'ZH', label: 'ZH Zurigo' },
];
export const deductibleUnder26Options = [
  { value: 'Yes', label: 'automation.opt_ded26_yes' },
  { value: '0', label: 'automation.opt_ded26_no' },
  { value: '1000', label: 'automation.opt_ded26_1000' },
  { value: '2000', label: 'automation.opt_ded26_2000' },
  { value: '3000', label: 'automation.opt_ded26_3000' },
  { value: '5000', label: 'automation.opt_ded26_5000' },
];
export const siNoOptions = ['Yes', 'No'];
export const vehicleUsageOptions = [
  { value: 'no_specific_use', label: 'automation.opt_usage_none' },
  { value: 'freight_transport', label: 'automation.opt_usage_cargo' },
  { value: 'courier', label: 'automation.opt_usage_courier' },
  { value: 'passenger_transport', label: 'automation.opt_usage_passenger' },
  { value: 'taxi', label: 'automation.opt_usage_taxi' },
  { value: 'driving_school', label: 'automation.opt_usage_driving_school' },
  { value: 'rental', label: 'automation.opt_usage_rental' },
];
export const civilInsuranceOptions = [
  { value: 'Yes excluding my property', label: 'automation.opt_civil_yes_excl' },
  { value: 'Yes including my property', label: 'automation.opt_civil_yes_incl' },
  { value: 'No', label: 'automation.opt_civil_no' },
];
export const comprehensiveOptions = [
  { value: 'None', label: 'automation.opt_comp_none' },
  { value: 'Partial', label: 'automation.opt_comp_partial' },
  { value: 'Full', label: 'automation.opt_comp_total' },
];
export const deductibleTotalOptions = ['500', '1000', '2000'];
export const deductiblePartialOptions = ['0', '200', '500', '1000'];
export const parkingDamageOptions = [
  { value: 'No', label: 'automation.opt_park_no' },
  { value: 'Unlimited', label: 'automation.opt_park_unlimited' },
  { value: '1000', label: 'automation.opt_park_1000' },
  { value: '2000', label: 'automation.opt_park_2000' },
];
export const deductibleParkingOptions = ['0', '200', '500'];
export const personalBelongingsOptions = [
  { value: 'No', label: 'automation.opt_belong_no' },
  { value: '2000', label: 'automation.opt_belong_2000' },
  { value: '3000', label: 'automation.opt_belong_3000' },
  { value: '5000', label: 'automation.opt_belong_5000' },
];
export const garageFreeOptions = [
  { value: 'fixed', label: 'automation.opt_garage_fixed' },
  { value: 'free_choice', label: 'automation.opt_garage_choice' },
];
export const paymentModeOptions = [
  { value: 'Annual', label: 'automation.opt_payment_annual' },
  { value: 'Semiannual', label: 'automation.opt_payment_semi' },
];
export const licenseSuspensionOptions = [
  { value: 'none',              label: 'automation.opt_license_susp_none' },
  { value: '1 month',           label: 'automation.opt_license_susp_1m' },
  { value: '2 months',          label: 'automation.opt_license_susp_2m' },
  { value: '3 months or more',  label: 'automation.opt_license_susp_3m_plus' },
];
export const claimsOptions = ['0', '1', '2', '3'];

// ─── Nuove option arrays (allineamento contratto API) ───────────────────────
export const vehicleTypeOptions = [
  { value: '', label: 'automation.form_select_placeholder' },
  { value: 'passenger_car', label: 'automation.opt_vtype_passenger_car' },
  { value: 'van', label: 'automation.opt_vtype_van' },
];
export const driveOptions = [
  { value: '', label: 'automation.form_select_placeholder' },
  { value: 'Benzin', label: 'automation.opt_drive_benzin' },
  { value: 'Diesel', label: 'automation.opt_drive_diesel' },
  { value: 'Hybrid-Benzin', label: 'automation.opt_drive_hybrid_benzin' },
  { value: 'Hybrid-Diesel', label: 'automation.opt_drive_hybrid_diesel' },
  { value: 'Electric', label: 'automation.opt_drive_electric' },
];
export const kmPerYearOptions = [
  { value: '', label: 'automation.form_select_placeholder' },
  { value: '5000', label: '5\'000' },
  { value: '7000', label: '7\'000' },
  { value: '10000', label: '10\'000' },
  { value: '15000', label: '15\'000' },
  { value: '20000', label: '20\'000' },
  { value: '25000', label: '25\'000' },
  { value: '30000', label: '30\'000' },
  { value: '+30000', label: '+30\'000' },
];
export const reasonsForRedemptionOptions = [
  { value: '', label: 'automation.form_select_placeholder' },
  { value: 'New redemption', label: 'automation.opt_reason_new' },
  { value: 'Vehicle change', label: 'automation.opt_reason_vehicle_change' },
  { value: 'Vehicle change in the interchangeable sign', label: 'automation.opt_reason_vehicle_change_inter' },
  { value: 'Open interchangeable sign', label: 'automation.opt_reason_open_inter' },
  { value: 'Change of ownership', label: 'automation.opt_reason_ownership' },
  { value: 'Changing insurers without changing vehicles', label: 'automation.opt_reason_change_insurers' },
  { value: 'other cases', label: 'automation.opt_reason_other' },
];
export const submitVehicleProofOptions = [
  { value: '', label: 'automation.form_select_placeholder' },
  { value: 'Yes', label: 'automation.form_yes' },
  { value: 'No', label: 'automation.form_no' },
];
export const driverTypeOptions = [
  { value: 'user', label: 'automation.opt_driver_user' },
  { value: 'other', label: 'automation.opt_driver_other' },
  { value: 'multiple', label: 'automation.opt_driver_multiple' },
];
// LeasingCompany enum estratto da openapi.json (components.schemas.LeasingCompany.enum) — 123 voci
export const leasingCompanyOptions = [
  'A+A Leasing AG', 'a2B Leasing & Finance AG', 'AGCO Finance AG', 'AGLF AG for Agricultural Financing',
  'AIL Swiss-Austria Leasing AG', 'ALB AG Car Leasing & Consulting', 'ALD Automotive AG', 'Allane Schweiz AG',
  'ALLMECO Leasing GmH, Unterhaching', 'Alphabet Fleet Management Switzerland Ltd.', 'Alphera Financial Services',
  'AMAG Leasing AG', 'ARVAL (Switzerland) AG', 'ASL Auto Service-Leasing AG',
  'Audi Leasing branch office, D-Braunschweig', 'Auto-Interleasing AG, 4132 Muttenz',
  'Auto-Interleasing AG, 8902 Urdorf', 'Ayvens Switzerland AG',
  'Bank11 for Private Customers and Trade GmbH, D-Neuss', 'Bank-now AG', 'Banque cantonale de Genève',
  'Banque CIC (Suisse) SA', 'BAWAG PSK Leasing GmbH, A-Vienna', 'Binelli & Ehrsam AG',
  'BMW Financial Services (Switzerland) AG', 'BNP Paribas Leasing Solutions Suisse SA',
  'BPCE Equipment Solutions Switzerland AG', 'BTV Leasing Switzerland AG', 'BUGA Finanz AG',
  'CA Auto Finance Suisse SA', 'Carauktion AG', 'Cariva AG',
  'Caterpillar Financial Services GmbH, D-Ismaning', 'Cembra Money Bank (ex Cashgate AG)',
  'Cembra Money Bank AG', 'CoOpera Leasing AG', 'Credit Suisse',
  'Credit Suisse (Switzerland) AG, 1003 Lausanne', 'DL Location Leasing SA', 'EFL Autoleasing AG',
  'Emil Frey AG, 8048 Zurich', 'Emil Frey AG, 8050 Zurich',
  'Erste Bank und Sparkassen Leasing GmbH, A-Vienna', 'Europa-Leasing GmbH, D-Kieselbronn',
  'Ferrari Financial Services AG, D-Grünwald/Munich', 'FGA Bank Germany GmbH, D-Heilbronn',
  'Fical Finance AG, 5432, Neuenhof', 'Fire Auto Leasing AG', 'Flexikredit AG', 'FML Leasing AG',
  'Ford Credit (Switzerland) GmbH', 'Ford Credit Europe (FCE)', 'Fortis Lease Suisse SA', 'Franz AG',
  'General Motors Financial Suisse SA', 'Genève Crédit & Leasing SA', 'HARLA Leasing AG',
  'HIL Mobilienleasing GmbH & Co KG, A-Dornbirn', 'Honda (Suisse) SA',
  'Hypo Immobilien & Leasing GmbH, A-Dornbirn', 'Hypo SüdLeasing GmbH, A-Dornbirn',
  'IG Leasing AG (ex Siemens Leasing AG)', 'IMPA Leasing AG', 'IVECO FINANCE AG',
  'LeaseForce AG', 'lease it ag', 'Lease Plan (Switzerland) AG', 'LeaseTeq AG',
  'Leasfinanz GmbH, A-Vienna', 'Leasing-west GmbH, D-Kiefersfelden', 'Leasinvest AG, 9496 Balzers',
  'Leasinvest AG (Switzerland), 9477 Trübbach', 'Lepo Leasing AG', 'Loancar AG',
  'MAN Financial Services GmbH, D-Munich', 'Maserati Financial Services',
  'Mercedes-Benz Bank AG, D-Saarbrücken', 'Mercedes-Benz Financial Services Switzerland AG',
  'MF Fleetmanagement AG', 'Migros Bank AG', 'Mobility Solutions AG',
  'movon AG, 6330 Cham', 'Multilease AG, 1110 Morges', 'Multilease AG, 4624 Härkingen',
  'Multilease AG, 8152 Glattbrugg', 'Multilease AG, 9000 St. Gallen',
  'Multilease AG (Toyota Prius), 8048 Zurich', 'N+C Leasing AG', 'Neumühle Handels AG',
  'Nissan Finance', 'Norddeutsche Landesbank, D-Hannover', 'Opel Finance AG', 'PhG LeasCo',
  'Pierre Sudan Leasing and Finance AG', 'Porsche Financial Services Switzerland AG',
  'Post Company Cars AG', 'PSA Finance Belux SA, B-Bruxelles', 'Raiffeisen Leasing', 'RCI Finance SA',
  'Renault Trucks Financial Services (trucks only)', 'SAM Swiss AG for Mobility',
  'Santander Consumer Bank, D-Mönchengladbach', 'Santander Consumer Finance Switzerland AG',
  'Scania Finance Switzerland AG', 'Scania Leasing Austria Ltd.', 'Settelen AG',
  'SG Equipment Finance Switzerland AG', 'Sixt Leasing (Switzerland) AG', 'SüdLeasing Suisse AG',
  'Swiss Car Finance AG / SsangYong Switzerland AG', 'Swissquote Bank SA', 'TIBERIS AG',
  'UBS Leasing AG', 'Unifin 98 AG', 'Valiant Bank AG', 'Volksbank Rottweil eG, D-Rottweil',
  'Volksbank Vorarlberg Anlagen-Leasing GmbH, A-Rankweil', 'Volkswagen Leasing GmbH, D-Braunschweig',
  'Volvo Finance (Switzerland) AG (trucks only)', 'Vorarlberg State and Mortgage Bank AG, A-Bregenz',
  'Windlin Leasing AG', 'Würth Leasing AG', 'Zurich Cantonal Bank Leasing FS',
];
export const registrationScraperOptions: string[] = ['zurich', 'automate', 'helvetia', 'axa', 'mobiliar', 'allianz'];
